In [2]:
import pandas as pd
import plotly.express as px
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix,accuracy_score

# Import Data

In [3]:
datasets = pd.read_csv('bank_dataset.csv')
datasets.drop(['ID','ZIP Code'],axis=1,inplace=True)

new_customer = pd.read_csv('bank_new.csv')
new_customer.drop(['Personal Loan'],axis=1,inplace=True)
new_customer

,Age,Experience,Income,Family,CCAvg,Education,Mortgage,Securities Account,CD Account,Online,CreditCard
0,40,10,84,2,2,2,0,0,0,1,1

In [4]:
y_df = datasets[['Personal Loan']]
datasets.drop(['Personal Loan'],axis=1,inplace=True)
X_df = datasets
with pd.option_context('display.max_rows', 8): display(X_df)

,Age,Experience,Income,Family,CCAvg,Education,Mortgage,Securities Account,CD Account,Online,CreditCard
0,25,1,49,4,1.6,1,0,1,0,0,0
1,45,19,34,3,1.5,1,0,1,0,0,0
2,39,15,11,1,1.0,1,0,0,0,0,0
3,35,9,100,1,2.7,2,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
4996,30,4,15,4,0.4,1,85,0,0,1,0
4997,63,39,24,2,0.3,3,0,0,0,0,0
4998,65,40,49,3,0.5,2,0,0,0,1,0
4999,28,4,83,3,0.8,1,0,0,0,1,1

In [5]:
X = X_df.values
y = y_df.values

# Preprocess

In [6]:
scaler = StandardScaler()
X_norm = scaler.fit_transform(X)
new = new_customer.values
new = scaler.transform(new)

# K-NN k=5 --> เปลี่ยน k ตามโจทย์หรือตามที่ต้องการ

In [7]:
neigh = KNeighborsClassifier(n_neighbors=5,metric='euclidean')
neigh.fit(X_norm, y)

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

KNeighborsClassifier(metric='euclidean')

In [8]:
y_pred = neigh.predict(new)
print(y_pred)

[0]

# Find Best k K-NN

In [9]:
X_train , X_test , y_train , y_test = train_test_split(X,y,train_size=0.6,random_state=1992)

In [10]:
print(X_train)

[[ 58.  34.  11. ...   0.   1.   0.]
 [ 60.  35. 119. ...   0.   1.   0.]
 [ 28.   4.  34. ...   0.   1.   0.]
 ...
 [ 64.  40.  89. ...   0.   0.   0.]
 [ 49.  24. 138. ...   0.   1.   0.]
 [ 58.  32.  54. ...   0.   1.   1.]]

In [11]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [12]:
scores = []
for k in range(1,21):
  neigh = KNeighborsClassifier(n_neighbors=k,metric='euclidean')
  neigh.fit(X_train, y_train.ravel())
  scores.append([k,neigh.score(X_test,y_test)])

In [13]:
scores.sort(key=lambda x: x[1], reverse=True)
print(f"Best k={scores[0][0]} with accuracy score:{scores[0][1]}")

Best k=3 with accuracy score:0.9575

# Using Best k & Show Confusion Matrix

In [14]:
k = scores[0][0]
neigh = KNeighborsClassifier(n_neighbors=k,metric='euclidean')
neigh.fit(X_train, y_train.ravel())

KNeighborsClassifier(metric='euclidean', n_neighbors=3)

In [15]:
y_pred = neigh.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(classification_report(y_test,y_pred))

[[1792   11]
 [  74  123]]
              precision    recall  f1-score   support

           0       0.96      0.99      0.98      1803
           1       0.92      0.62      0.74       197

    accuracy                           0.96      2000
   macro avg       0.94      0.81      0.86      2000
weighted avg       0.96      0.96      0.95      2000

In [16]:
y_pred = neigh.predict(new)
print(y_pred)

[0]